// Generated by scripts/generate-dom-setters.js from TypeScript 5.9.3's
// lib.dom.d.ts. Do not edit.

/**
 * Settable properties of `HTMLElement` and its mixins, which every HTML
 * element has (`Element`'s own are left out, as the runtime's setter walk
 * leaves them out).
 */
export const HTML_ELEMENT_SETTERS = new Set(['accessKey', 'autocapitalize', 'autocorrect', 'autofocus', 'contentEditable', 'dir', 'draggable', 'enterKeyHint', 'hidden', 'inert', 'innerText', 'inputMode', 'lang', 'nonce', 'onabort', 'onanimationcancel', 'onanimationend', 'onanimationiteration', 'onanimationstart', 'onauxclick', 'onbeforeinput', 'onbeforematch', 'onbeforetoggle', 'onblur', 'oncancel', 'oncanplay', 'oncanplaythrough', 'onchange', 'onclick', 'onclose', 'oncontextlost', 'oncontextmenu', 'oncontextrestored', 'oncopy', 'oncuechange', 'oncut', 'ondblclick', 'ondrag', 'ondragend', 'ondragenter', 'ondragleave', 'ondragover', 'ondragstart', 'ondrop', 'ondurationchange', 'onemptied', 'onended', 'onerror', 'onfocus', 'onformdata', 'ongotpointercapture', 'oninput', 'oninvalid', 'onkeydown', 'onkeypress', 'onkeyup', 'onload', 'onloadeddata', 'onloadedmetadata', 'onloadstart', 'onlostpointercapture', 'onmousedown', 'onmouseenter', 'onmouseleave', 'onmousemove', 'onmouseout', 'onmouseover', 'onmouseup', 'onpaste', 'onpause', 'onplay', 'onplaying', 'onpointercancel', 'onpointerdown', 'onpointerenter', 'onpointerleave', 'onpointermove', 'onpointerout', 'onpointerover', 'onpointerrawupdate', 'onpointerup', 'onprogress', 'onratechange', 'onreset', 'onresize', 'onscroll', 'onscrollend', 'onsecuritypolicyviolation', 'onseeked', 'onseeking', 'onselect', 'onselectionchange', 'onselectstart', 'onslotchange', 'onstalled', 'onsubmit', 'onsuspend', 'ontimeupdate', 'ontoggle', 'ontouchcancel', 'ontouchend', 'ontouchmove', 'ontouchstart', 'ontransitioncancel', 'ontransitionend', 'ontransitionrun', 'ontransitionstart', 'onvolumechange', 'onwaiting', 'onwebkitanimationend', 'onwebkitanimationiteration', 'onwebkitanimationstart', 'onwebkittransitionend', 'onwheel', 'outerText', 'popover', 'spellcheck', 'tabIndex', 'title', 'translate', 'writingSuggestions']);

/**
 * The settable properties an HTML element interface adds to
 * {@link HTML_ELEMENT_SETTERS}, by tag name; a tag not listed adds none.
 * @type {Record<string, readonly string[]>}
 */
export const HTML_TAG_SETTERS = {
	a: ['charset', 'coords', 'download', 'hash', 'host', 'hostname', 'href', 'hreflang', 'name', 'password', 'pathname', 'ping', 'port', 'protocol', 'referrerPolicy', 'rel', 'rev', 'search', 'shape', 'target', 'text', 'type', 'username'],
	area: ['alt', 'coords', 'download', 'hash', 'host', 'hostname', 'href', 'noHref', 'password', 'pathname', 'ping', 'port', 'protocol', 'referrerPolicy', 'rel', 'search', 'shape', 'target', 'username'],
	audio: ['autoplay', 'controls', 'crossOrigin', 'currentTime', 'defaultMuted', 'defaultPlaybackRate', 'disableRemotePlayback', 'loop', 'muted', 'onencrypted', 'onwaitingforkey', 'playbackRate', 'preload', 'preservesPitch', 'src', 'srcObject', 'volume'],
	base: ['href', 'target'],
	blockquote: ['cite'],
	body: ['aLink', 'background', 'bgColor', 'link', 'onafterprint', 'onbeforeprint', 'onbeforeunload', 'ongamepadconnected', 'ongamepaddisconnected', 'onhashchange', 'onlanguagechange', 'onmessage', 'onmessageerror', 'onoffline', 'ononline', 'onpagehide', 'onpagereveal', 'onpageshow', 'onpageswap', 'onpopstate', 'onrejectionhandled', 'onstorage', 'onunhandledrejection', 'onunload', 'text', 'vLink'],
	br: ['clear'],
	button: ['disabled', 'formAction', 'formEnctype', 'formMethod', 'formNoValidate', 'formTarget', 'name', 'popoverTargetAction', 'popoverTargetElement', 'type', 'value'],
	canvas: ['height', 'width'],
	caption: ['align'],
	col: ['align', 'ch', 'chOff', 'span', 'vAlign', 'width'],
	colgroup: ['align', 'ch', 'chOff', 'span', 'vAlign', 'width'],
	data: ['value'],
	del: ['cite', 'dateTime'],
	details: ['name', 'open'],
	dialog: ['open', 'returnValue'],
	div: ['align'],
	dl: ['compact'],
	embed: ['align', 'height', 'name', 'src', 'type', 'width'],
	fieldset: ['disabled', 'name'],
	form: ['acceptCharset', 'action', 'autocomplete', 'encoding', 'enctype', 'method', 'name', 'noValidate', 'rel', 'target'],
	h1: ['align'],
	h2: ['align'],
	h3: ['align'],
	h4: ['align'],
	h5: ['align'],
	h6: ['align'],
	hr: ['align', 'color', 'noShade', 'size', 'width'],
	html: ['version'],
	iframe: ['align', 'allow', 'allowFullscreen', 'frameBorder', 'height', 'loading', 'longDesc', 'marginHeight', 'marginWidth', 'name', 'referrerPolicy', 'scrolling', 'src', 'srcdoc', 'width'],
	img: ['align', 'alt', 'border', 'crossOrigin', 'decoding', 'fetchPriority', 'height', 'hspace', 'isMap', 'loading', 'longDesc', 'lowsrc', 'name', 'referrerPolicy', 'sizes', 'src', 'srcset', 'useMap', 'vspace', 'width'],
	input: ['accept', 'align', 'alt', 'autocomplete', 'capture', 'checked', 'defaultChecked', 'defaultValue', 'dirName', 'disabled', 'files', 'formAction', 'formEnctype', 'formMethod', 'formNoValidate', 'formTarget', 'height', 'indeterminate', 'max', 'maxLength', 'min', 'minLength', 'multiple', 'name', 'pattern', 'placeholder', 'popoverTargetAction', 'popoverTargetElement', 'readOnly', 'required', 'selectionDirection', 'selectionEnd', 'selectionStart', 'size', 'src', 'step', 'type', 'useMap', 'value', 'valueAsDate', 'valueAsNumber', 'webkitdirectory', 'width'],
	ins: ['cite', 'dateTime'],
	label: ['htmlFor'],
	legend: ['align'],
	li: ['type', 'value'],
	link: ['as', 'charset', 'crossOrigin', 'disabled', 'fetchPriority', 'href', 'hreflang', 'imageSizes', 'imageSrcset', 'integrity', 'media', 'referrerPolicy', 'rel', 'rev', 'target', 'type'],
	map: ['name'],
	menu: ['compact'],
	meta: ['content', 'httpEquiv', 'media', 'name', 'scheme'],
	meter: ['high', 'low', 'max', 'min', 'optimum', 'value'],
	object: ['align', 'archive', 'border', 'code', 'codeBase', 'codeType', 'data', 'declare', 'height', 'hspace', 'name', 'standby', 'type', 'useMap', 'vspace', 'width'],
	ol: ['compact', 'reversed', 'start', 'type'],
	optgroup: ['disabled', 'label'],
	option: ['defaultSelected', 'disabled', 'label', 'selected', 'text', 'value'],
	output: ['defaultValue', 'name', 'value'],
	p: ['align'],
	pre: ['width'],
	progress: ['max', 'value'],
	q: ['cite'],
	script: ['async', 'charset', 'crossOrigin', 'defer', 'event', 'fetchPriority', 'htmlFor', 'integrity', 'noModule', 'referrerPolicy', 'src', 'text', 'type'],
	select: ['autocomplete', 'disabled', 'length', 'multiple', 'name', 'required', 'selectedIndex', 'size', 'value'],
	slot: ['name'],
	source: ['height', 'media', 'sizes', 'src', 'srcset', 'type', 'width'],
	style: ['disabled', 'media', 'type'],
	table: ['align', 'bgColor', 'border', 'caption', 'cellPadding', 'cellSpacing', 'frame', 'rules', 'summary', 'tFoot', 'tHead', 'width'],
	tbody: ['align', 'ch', 'chOff', 'vAlign'],
	td: ['abbr', 'align', 'axis', 'bgColor', 'ch', 'chOff', 'colSpan', 'headers', 'height', 'noWrap', 'rowSpan', 'scope', 'vAlign', 'width'],
	template: ['shadowRootClonable', 'shadowRootDelegatesFocus', 'shadowRootMode', 'shadowRootSerializable'],
	textarea: ['autocomplete', 'cols', 'defaultValue', 'dirName', 'disabled', 'maxLength', 'minLength', 'name', 'placeholder', 'readOnly', 'required', 'rows', 'selectionDirection', 'selectionEnd', 'selectionStart', 'value', 'wrap'],
	tfoot: ['align', 'ch', 'chOff', 'vAlign'],
	th: ['abbr', 'align', 'axis', 'bgColor', 'ch', 'chOff', 'colSpan', 'headers', 'height', 'noWrap', 'rowSpan', 'scope', 'vAlign', 'width'],
	thead: ['align', 'ch', 'chOff', 'vAlign'],
	time: ['dateTime'],
	title: ['text'],
	tr: ['align', 'bgColor', 'ch', 'chOff', 'vAlign'],
	track: ['default', 'kind', 'label', 'src', 'srclang'],
	ul: ['compact', 'type'],
	video: ['autoplay', 'controls', 'crossOrigin', 'currentTime', 'defaultMuted', 'defaultPlaybackRate', 'disablePictureInPicture', 'disableRemotePlayback', 'height', 'loop', 'muted', 'onencrypted', 'onenterpictureinpicture', 'onleavepictureinpicture', 'onwaitingforkey', 'playbackRate', 'playsInline', 'poster', 'preload', 'preservesPitch', 'src', 'srcObject', 'volume', 'width'],
};

/** Every tag of `HTMLElementTagNameMap`. */
export const HTML_TAGS = new Set(['a', 'abbr', 'address', 'area', 'article', 'aside', 'audio', 'b', 'base', 'bdi', 'bdo', 'blockquote', 'body', 'br', 'button', 'canvas', 'caption', 'cite', 'code', 'col', 'colgroup', 'data', 'datalist', 'dd', 'del', 'details', 'dfn', 'dialog', 'div', 'dl', 'dt', 'em', 'embed', 'fieldset', 'figcaption', 'figure', 'footer', 'form', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'head', 'header', 'hgroup', 'hr', 'html', 'i', 'iframe', 'img', 'input', 'ins', 'kbd', 'label', 'legend', 'li', 'link', 'main', 'map', 'mark', 'menu', 'meta', 'meter', 'nav', 'noscript', 'object', 'ol', 'optgroup', 'option', 'output', 'p', 'picture', 'pre', 'progress', 'q', 'rp', 'rt', 'ruby', 's', 'samp', 'script', 'search', 'section', 'select', 'slot', 'small', 'source', 'span', 'strong', 'style', 'sub', 'summary', 'sup', 'table', 'tbody', 'td', 'template', 'textarea', 'tfoot', 'th', 'thead', 'time', 'title', 'tr', 'track', 'u', 'ul', 'var', 'video', 'wbr']);
