/** @import { ResolvedConfig } from 'vite' */
/** @import { ModuleEntry, RootBoundaryConfig } from '@ripple-ts/vite-plugin' */

import fs from 'node:fs';
import path from 'node:path';
import { get_route_entry_export_name, get_route_entry_path } from './routes.js';

/** @type {Map<string, string>} */
const generated_file_cache = new Map();

/**
 * @param {ResolvedConfig} viteConfig
 * @returns {string}
 */
export function get_project_generated_dir(viteConfig) {
	return path.join(viteConfig.cacheDir, 'project');
}

/**
 * @param {ResolvedConfig} viteConfig
 * @param {string} name
 * @param {string} source
 * @returns {string}
 */
export function write_project_generated_file(viteConfig, name, source) {
	const dir = get_project_generated_dir(viteConfig);
	const file = path.join(dir, name);

	if (generated_file_cache.get(file) === source && fs.existsSync(file)) {
		return file;
	}

	fs.mkdirSync(dir, { recursive: true });
	if (!fs.existsSync(file) || fs.readFileSync(file, 'utf-8') !== source) {
		fs.writeFileSync(file, source);
	}
	generated_file_cache.set(file, source);
	return file;
}

/**
 * The browser's hydration entry. It imports the page modules and the modules
 * ripple.config.ts names for the client (transport, root boundary), never the
 * config itself: the config holds the adapter, middlewares and whatever
 * server-only code they import. The server names the matched route's entry
 * and layout in `__ripple_data`.
 *
 * @param {{ staticEntries: string[], transport?: ModuleEntry, rootBoundary?: RootBoundaryConfig }} options
 * @returns {string}
 */
export function create_client_entry_source(options) {
	const { transport, rootBoundary = {} } = options;
	const static_imports = options.staticEntries
		.map((entry) => `  ${JSON.stringify(entry)}: () => import(${JSON.stringify(entry)}),`)
		.join('\n');

	const imports = [`import { hydrate, mount${transport ? ', setTransport' : ''} } from 'ripple';`];
	/** @type {string[]} */
	const boundary_entries = [];
	for (const key of /** @type {const} */ (['pending', 'catch'])) {
		const entry = rootBoundary[key];
		if (entry === undefined) continue;
		imports.push(`import * as ${key}Module from ${JSON.stringify(get_route_entry_path(entry))};`);
		boundary_entries.push(
			`  ${key}: getComponentExport(${key}Module, ${JSON.stringify(get_route_entry_export_name(entry))}),`,
		);
	}
	if (transport) {
		const export_name = get_route_entry_export_name(transport) ?? 'default';
		imports.push(
			`import * as transportModule from ${JSON.stringify(get_route_entry_path(transport))};`,
			'',
			`setTransport(transportModule[${JSON.stringify(export_name)}]);`,
		);
	}
	const root_boundary =
		boundary_entries.length > 0 ? `{\n${boundary_entries.join('\n')}\n}` : 'undefined';

	return `// Auto-generated by @ripple-ts/vite-plugin.
// This file is written to Vite's cacheDir/project folder.

${imports.join('\n')}

const routeModules = {
${static_imports}
};

const rootBoundary = ${root_boundary};

function getRouteEntryPath(entry) {
  return Array.isArray(entry) ? entry[1] : entry;
}

function getRouteEntryExportName(entry) {
  return Array.isArray(entry) ? entry[0] : undefined;
}

function getComponentExport(module, exportName) {
  if (exportName && typeof module[exportName] === 'function') return module[exportName];
  if (typeof module.default === 'function') return module.default;
  return Object.entries(module).find(([key, value]) => typeof value === 'function' && /^[A-Z]/.test(key))?.[1];
}

async function resolveRouteComponent(data) {
  const entryPath = getRouteEntryPath(data.entry);
  const exportName = getRouteEntryExportName(data.entry);
  if (!entryPath) return null;

  const loadModule = routeModules[entryPath] ?? (() => import(/* @vite-ignore */ entryPath));
  const Component = getComponentExport(await loadModule(), exportName);
  if (!Component) return null;

  // Load the route layout so hydration sees the same component tree as the
  // server render and the layout's CSS is part of the client graph.
  const layoutPath = data.layout;
  if (layoutPath) {
    const loadLayout = routeModules[layoutPath] ?? (() => import(/* @vite-ignore */ layoutPath));
    const Layout = getComponentExport(await loadLayout());
    if (Layout) return { Component, Layout };
  }

  return { Component };
}

(async () => {
  try {
    const data = JSON.parse(document.getElementById('__ripple_data').textContent);
    const target = document.getElementById('root');
    const resolved = await resolveRouteComponent(data);

    if (!resolved || !target) {
      console.error('[ripple] Unable to hydrate route: missing component export or #root target.');
      return;
    }

    // With a layout, hydrate the layout and pass the page as its children
    // prop — the same tree the server rendered.
    const { Component, Layout } = resolved;
    const pageProps = { params: data.params };
    const root = Layout ?? Component;
    const props = Layout ? { ...pageProps, children: () => Component(pageProps) } : pageProps;

    try {
      hydrate(root, { target, props, rootBoundary });
    } catch (error) {
      console.warn('[ripple] Hydration failed, falling back to mount.', error);
      mount(root, { target, props, rootBoundary });
    }
  } catch (error) {
    console.error('[ripple] Failed to bootstrap client hydration.', error);
  }
})();
`;
}
